
import { Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "./ToastNext";
import 'react-toastify/dist/ReactToastify.css';
import {ThemeProvider} from '../app/Contaxt/ThemeContext'
const poppins = Poppins({ subsets: ["latin-ext"], weight:["400" , "700"]  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={poppins.className}>
      <ThemeProvider >
      {children}

      </ThemeProvider>
      

      <ToastContainer/>
      </body>
    </html>
  );
}
